window.PRELOADED_COVERS = {
  "5": "https://cdn.mangaupdates.com/image/i177814.jpg",
  "fist of the north star": "https://cdn.mangaupdates.com/image/i537014.jpg",
  "city hunter (complete edition)": "https://cdn.mangaupdates.com/image/i228711.jpg",
  "city hunter": "https://cdn.mangaupdates.com/image/i228711.jpg",
  "detektif conan premium": "https://cdn.mangaupdates.com/image/i537941.jpg",
  "shaman king": "https://cdn.mangaupdates.com/image/i385606.jpg",
  "black clover": "https://cdn.mangaupdates.com/image/i534037.jpg",
  "dragon ball super": "https://cdn.mangaupdates.com/image/i482614.jpg",
  "q.e.d. iff": "https://cdn.mangaupdates.com/image/i483325.jpg",
  "hanako si arwah penasaran (bookpaper)": "https://cdn.mangaupdates.com/image/i526740.jpg",
  "hanako si arwah penasaran": "https://cdn.mangaupdates.com/image/i526740.jpg",
  "haikyu! fly high volleyball!": "https://cdn.mangaupdates.com/image/i327729.png",
  "tokyo revengers": "https://cdn.mangaupdates.com/image/i405719.jpg",
  "teasing master, takagi": "https://cdn.mangaupdates.com/image/i528872.jpg",
  "the quintessential quintuplets": "https://cdn.mangaupdates.com/image/i534324.jpg",
  "detektif kindaichi 37 tahun": "https://cdn.mangaupdates.com/image/i474213.jpg",
  "moriarty the patriot": "https://cdn.mangaupdates.com/image/i534722.jpg",
  "dr. slump (bunkoban)": "https://cdn.mangaupdates.com/image/i527486.jpg",
  "dr. slump": "https://cdn.mangaupdates.com/image/i527486.jpg",
  "mob psycho 100": "https://cdn.mangaupdates.com/image/i534297.jpg",
  "bakemonogatari": "https://cdn.mangaupdates.com/image/i528199.jpg",
  "detektif kindaichi premium": "https://cdn.mangaupdates.com/image/i225185.png",
  "wotakoi: love is hard for otaku": "https://cdn.mangaupdates.com/image/i507192.jpg",
  "futo detective": "https://cdn.mangaupdates.com/image/i525784.jpg",
  "dead mount death play": "https://cdn.mangaupdates.com/image/i522333.jpg",
  "frieren: after the end": "https://cdn.mangaupdates.com/image/i525134.jpg",
  "sakamoto days": "https://cdn.mangaupdates.com/image/i532619.jpg",
  "kanojo okarishimasu": "https://cdn.mangaupdates.com/image/i529803.jpg",
  "bungo stray dogs": "https://cdn.mangaupdates.com/image/i516217.jpg",
  "a couple of cuckoos": "https://cdn.mangaupdates.com/image/i529812.png",
  "one room of happiness": "https://cdn.mangaupdates.com/image/i403376.jpg",
  "final fantasy: lost stranger": "https://cdn.mangaupdates.com/image/i523864.jpg",
  "fate/strange fake": "https://cdn.mangaupdates.com/image/i340076.jpg",
  "hibiki: kiat menjadi novelis": "https://cdn.mangaupdates.com/image/i302158.jpg",
  "samurai x: hokkaido arc": "https://cdn.mangaupdates.com/image/i526752.jpg",
  "alice in borderland": "https://cdn.mangaupdates.com/image/i245817.png",
  "dr. stone": "https://cdn.mangaupdates.com/image/i535298.jpg",
  "kubo won't let me be invisible": "https://cdn.mangaupdates.com/image/i412859.jpg",
  "blood lad": "https://cdn.mangaupdates.com/image/i248180.jpg",
  "mashle": "https://cdn.mangaupdates.com/image/i428606.jpg",
  "gokushufudo - the way of house husband": "https://cdn.mangaupdates.com/image/i527001.jpg",
  "one week friends": "https://cdn.mangaupdates.com/image/i524143.jpg",
  "smile at the runway": "https://cdn.mangaupdates.com/image/i358482.jpg",
  "the promised neverland": "https://cdn.mangaupdates.com/image/i518153.jpg",
  "the skull starts moving in the dark night": "https://cdn.mangaupdates.com/image/i306672.jpg",
  "yotsuba&!": "https://cdn.mangaupdates.com/image/i475257.png",
  "c.m.b.": "https://cdn.mangaupdates.com/image/i335242.jpg",
  "the memorandum of kyoko okitegami": "https://cdn.mangaupdates.com/image/i524018.jpg",
  "my name is a": "https://cdn.mangaupdates.com/image/i409000.jpg",
  "another": "https://cdn.mangaupdates.com/image/i526254.jpg",
  "shiomi-chan": "https://cdn.mangaupdates.com/image/i485820.jpg",
  "barefoot gen": "https://cdn.mangaupdates.com/image/i211872.jpg",
  "say hello to black jack": "https://cdn.mangaupdates.com/image/i413654.jpg",
  "sket dance": "https://cdn.mangaupdates.com/image/i476092.png",
  "i want to eat your pancreass": "https://cdn.mangaupdates.com/image/i407884.jpg",
  "record of ragnarok": "https://cdn.mangaupdates.com/image/i534711.jpg",
  "demon slayer: kimetsu no yaiba": "https://cdn.mangaupdates.com/image/i525117.jpg",
  "chainsaw man": "https://cdn.mangaupdates.com/image/i534295.png",
  "hellsing": "https://cdn.mangaupdates.com/image/i528506.jpg",
  "jujutsu kaisen": "https://cdn.mangaupdates.com/image/i470074.jpg",
  "the apothecary diaries": "https://cdn.mangaupdates.com/image/i535944.png",
  "erased": "https://cdn.mangaupdates.com/image/i525627.jpg",
  "trace: recollections of a forensic researcher": "https://cdn.mangaupdates.com/image/i487987.jpg",
  "komikus shojo nozaki": "https://cdn.mangaupdates.com/image/i532361.jpg",
  "aku no hana : kembang jahanam": "https://cdn.mangaupdates.com/image/i188148.jpg",
  "the journey of elaina": "https://cdn.mangaupdates.com/image/i380031.jpg",
  "my capricorn friend": "https://cdn.mangaupdates.com/image/i313952.png",
  "hideout": "https://cdn.mangaupdates.com/image/i95362.png",
  "tokyo ghoul": "https://cdn.mangaupdates.com/image/i208080.jpg",
  "blue box": "https://cdn.mangaupdates.com/image/i530462.jpg",
  "ragna crimson": "https://cdn.mangaupdates.com/image/i525454.jpg",
  "kaguya-sama: love is war": "https://cdn.mangaupdates.com/image/i454237.jpg",
  "edens zero": "https://cdn.mangaupdates.com/image/i495919.jpg",
  "spy x family": "https://cdn.mangaupdates.com/image/i520427.jpg",
  "re: zero - starting life in another world - chapter 2: a week at the mansion": "https://cdn.mangaupdates.com/image/i530014.jpg",
  "oshi no ko: anak idola": "https://cdn.mangaupdates.com/image/i496269.jpg",
  "attack on titan before the fall": "https://cdn.mangaupdates.com/image/i289127.jpg",
  "after the rain": "https://cdn.mangaupdates.com/image/i127896.png",
  "city hunter rebirth": "https://cdn.mangaupdates.com/image/i477575.jpg",
  "tokyo ghoul: re": "https://cdn.mangaupdates.com/image/i245117.jpg",
  "cells at work!": "https://cdn.mangaupdates.com/image/i527971.jpg",
  "cells at work! black": "https://cdn.mangaupdates.com/image/i336853.jpg",
  "my hero academia": "https://cdn.mangaupdates.com/image/i505247.jpg",
  "the king's beast": "https://cdn.mangaupdates.com/image/i492525.jpg",
  "when you wish upon a star": "https://cdn.mangaupdates.com/image/i163715.jpg",
  "the eternal zero": "https://cdn.mangaupdates.com/image/i152806.png",
  "just the two of us": "https://cdn.mangaupdates.com/image/i535106.jpg",
  "blue lock": "https://cdn.mangaupdates.com/image/i525653.jpg",
  "second summer, never see you again": "https://cdn.mangaupdates.com/image/i290956.jpg",
  "my youth romantic comedy is wrong as i expected": "https://cdn.mangaupdates.com/image/i502075.jpg",
  "look forward for the next death game": "https://cdn.mangaupdates.com/image/i290075.jpg",
  "ship of theseus": "https://cdn.mangaupdates.com/image/i312345.png",
  "neon genesis evangelion": "https://cdn.mangaupdates.com/image/i528437.jpg",
  "happiness": "https://cdn.mangaupdates.com/image/i172224.jpg",
  "lunar legend tsukihime": "https://cdn.mangaupdates.com/image/i503261.jpg",
  "death note": "https://cdn.mangaupdates.com/image/i295749.jpg",
  "overlord": "https://cdn.mangaupdates.com/image/i450910.jpg",
  "chiruran, shinsengumi requiem": "https://cdn.mangaupdates.com/image/i421558.jpg",
  "pseudo harem": "https://cdn.mangaupdates.com/image/i340922.jpg",
  "she is more ordinary that i expected": "https://cdn.mangaupdates.com/image/i255814.jpg",
  "godhand teru: the silence corona 2020": "https://cdn.mangaupdates.com/image/i379395.jpg",
  "the blue orchestra": "https://cdn.mangaupdates.com/image/i520766.jpg",
  "chion and the cat temple": "https://cdn.mangaupdates.com/image/i285239.jpg",
  "jojo's bizzare adventure": "https://cdn.mangaupdates.com/image/i402392.jpg",
  "boruto - naruto next generation": "https://cdn.mangaupdates.com/image/i526262.jpg",
  "hiroshi nohara's lunch style": "https://cdn.mangaupdates.com/image/i499138.jpg",
  "youth x machine gun - aoharu x kikanjuu": "https://cdn.mangaupdates.com/image/i297908.jpg",
  "h2o: reborn (omnibus)": "https://cdn.mangaupdates.com/image/i525093.jpg",
  "h2o: reborn": "https://cdn.mangaupdates.com/image/i525093.jpg",
  "slam dunk new edition (satuan)": "https://cdn.mangaupdates.com/image/i426096.png",
  "slam dunk new edition": "https://cdn.mangaupdates.com/image/i426096.png",
  "who is to blame: the bully, or the bullied": "https://cdn.mangaupdates.com/image/i456302.jpg",
  "mitsume cleaned the plates again today": "https://cdn.mangaupdates.com/image/i276147.jpg",
  "jurnal mukai usagido": "https://cdn.mangaupdates.com/image/i528601.jpg",
  "that summer 1959": "https://cdn.mangaupdates.com/image/i271609.jpg",
  "revenge club": "https://cdn.mangaupdates.com/image/i307340.jpg",
  "actor wannabe endo-kun": "https://cdn.mangaupdates.com/image/i270669.jpg",
  "hanyut": "https://cdn.mangaupdates.com/image/i158259.jpg",
  "one room of happiness spin-off: the corrupted detective": "https://cdn.mangaupdates.com/image/i343530.jpg",
  "aquatic company!": "https://cdn.mangaupdates.com/image/i236638.png",
  "doraemon story -fujiko f fujio figure-": "https://cdn.mangaupdates.com/image/i413705.jpg",
  "shanghai white snake mansion mysteries": "https://cdn.mangaupdates.com/image/i365954.jpg",
  "pulau dalam genangan air": "https://cdn.mangaupdates.com/image/i379491.jpg",
  "a terrified teacher at ghost school!": "https://cdn.mangaupdates.com/image/i525781.jpg",
  "honda, are you alive?": "https://cdn.mangaupdates.com/image/i265621.jpg",
  "the escape game": "https://cdn.mangaupdates.com/image/i485057.jpg",
  "higehiro: after being rejected, i shaved and took in a highschool runaway": "https://cdn.mangaupdates.com/image/i285917.jpg",
  "the irregular at magic high school - enrollment arc": "https://cdn.mangaupdates.com/image/i494609.jpg",
  "detective xeno and the seven locked murder rooms": "https://cdn.mangaupdates.com/image/i297087.jpg",
  "perfect world": "https://cdn.mangaupdates.com/image/i71754.jpg",
  "fly me to the moon": "https://cdn.mangaupdates.com/image/i401974.jpg",
  "interview with monster girls": "https://cdn.mangaupdates.com/image/i231726.png",
  "the scary stories": "https://cdn.mangaupdates.com/image/i489684.jpg",
  "the birds of death": "https://cdn.mangaupdates.com/image/i290071.jpg",
  "lil' sis please cook for me": "https://cdn.mangaupdates.com/image/i264028.jpg",
  "cops & robbers": "https://cdn.mangaupdates.com/image/i326862.jpg",
  "smile": "https://cdn.mangaupdates.com/image/i168228.jpg",
  "mission : yozakura family": "https://cdn.mangaupdates.com/image/i475589.jpg",
  "restaurant to another world": "https://cdn.mangaupdates.com/image/i293497.jpg",
  "the misfit of demon king academy": "https://cdn.mangaupdates.com/image/i338245.jpg",
  "sword art online the movie - ordinal scale": "https://cdn.mangaupdates.com/image/i325288.jpg",
  "spring garden": "https://cdn.mangaupdates.com/image/i424392.jpg",
  "blue lock - episode nagi": "https://cdn.mangaupdates.com/image/i495245.jpg",
  "the liminal zone": "https://cdn.mangaupdates.com/image/i337625.jpg",
  "arakawa under the bridge": "https://cdn.mangaupdates.com/image/i528615.jpg",
  "attack on titan": "https://cdn.mangaupdates.com/image/i424594.png",
  "naruto": "https://cdn.mangaupdates.com/image/i140134.png",
  "delicious in dungeon": "https://cdn.mangaupdates.com/image/i530321.jpg",
  "fate/type redline: strange strory of imperial capital holy grail": "https://cdn.mangaupdates.com/image/i527036.jpg",
  "mujirushi: the sign of dreams": "https://cdn.mangaupdates.com/image/i278025.jpg",
  "the fragrant flower blooms with dignity - kaoru & rin": "https://cdn.mangaupdates.com/image/i536543.jpg",
  "classroom of the elite": "https://cdn.mangaupdates.com/image/i350851.jpg",
  "naruto side story: seventh hokage and the scarlet spring": "https://cdn.mangaupdates.com/image/i288837.png",
  "fullmetal alchemist 20th anniversary book": "https://cdn.mangaupdates.com/image/i508762.jpg",
  "detektif conan secret archives 1 shinichi kudo & ran mouri": "https://cdn.mangaupdates.com/image/i59051.jpg",
  "tari tari": "https://cdn.mangaupdates.com/image/i525643.jpg",
  "kaiju no. 8": "https://cdn.mangaupdates.com/image/i497577.jpg",
  "kemari, kota!": "https://cdn.mangaupdates.com/image/i317212.jpg",
  "taxi for pets": "https://cdn.mangaupdates.com/image/i329914.jpg",
  "burn the witch": "https://cdn.mangaupdates.com/image/i324669.jpg",
  "rascal does not dream of bunny girl senpai": "https://cdn.mangaupdates.com/image/i530100.jpg",
  "monster": "https://cdn.mangaupdates.com/image/i216517.png",
  "the evil collection": "https://cdn.mangaupdates.com/image/i258925.png",
  "papa and daddy's home cooking": "https://cdn.mangaupdates.com/image/i510588.png",
  "mao": "https://cdn.mangaupdates.com/image/i537943.jpg",
  "black bullet": "https://cdn.mangaupdates.com/image/i247690.jpg",
  "homunculus": "https://cdn.mangaupdates.com/image/i393645.jpg",
  "magical iroha": "https://cdn.mangaupdates.com/image/i517200.jpg",
  "our graduation": "https://cdn.mangaupdates.com/image/i221702.jpg",
  "recollection of a certain pilot": "https://cdn.mangaupdates.com/image/i208140.jpg",
  "my 17th spring": "https://cdn.mangaupdates.com/image/i214454.png",
  "butsu zone": "https://cdn.mangaupdates.com/image/i155785.jpg",
  "kuro memanggul peti mati": "https://cdn.mangaupdates.com/image/i537502.jpg",
  "working man": "https://cdn.mangaupdates.com/image/i195644.jpg",
  "the phantom tower": "https://cdn.mangaupdates.com/image/i251485.png",
  "the witch's best friend": "https://cdn.mangaupdates.com/image/i328896.jpg",
  "toto": "https://cdn.mangaupdates.com/image/i48092.jpg",
  "twin spica": "https://cdn.mangaupdates.com/image/i457259.png",
  "kure-nai": "https://cdn.mangaupdates.com/image/i528243.jpg",
  "rahxephon": "https://cdn.mangaupdates.com/image/i381997.jpg",
  "sarishinohara dear": "https://cdn.mangaupdates.com/image/i179940.jpg",
  "takahashi is hearing it": "https://cdn.mangaupdates.com/image/i259913.png",
  "sakura wars": "https://cdn.mangaupdates.com/image/i459583.jpg",
  "3x3 eyes": "https://cdn.mangaupdates.com/image/i77038.jpg",
  "words to give": "https://cdn.mangaupdates.com/image/i525648.jpg",
  "rainbow": "https://cdn.mangaupdates.com/image/i335694.jpg",
  "pingpong rush": "https://cdn.mangaupdates.com/image/i318034.jpg",
  "kome si belang": "https://cdn.mangaupdates.com/image/i511322.png",
  "deadman wonderland": "https://cdn.mangaupdates.com/image/i530609.jpg",
  "green blood": "https://cdn.mangaupdates.com/image/i193829.jpg",
  "planetes": "https://cdn.mangaupdates.com/image/i528997.jpg",
  "kasane": "https://cdn.mangaupdates.com/image/i231468.jpg",
  "aldnoah.zero": "https://cdn.mangaupdates.com/image/i218384.jpg",
  "a man & his cat": "https://cdn.mangaupdates.com/image/i526999.jpg",
  "white tower": "https://cdn.mangaupdates.com/image/i343277.jpg",
  "livingstone": "https://cdn.mangaupdates.com/image/i524842.jpg",
  "jinco from room 203": "https://cdn.mangaupdates.com/image/i221799.jpg",
  "eagle": "https://cdn.mangaupdates.com/image/i274040.png",
  "underground dogs": "https://cdn.mangaupdates.com/image/i225744.jpg",
  "bonnouji": "https://cdn.mangaupdates.com/image/i188293.jpg",
  "fantastic post office": "https://cdn.mangaupdates.com/image/i128393.jpg",
  "forest of wool and steel": "https://cdn.mangaupdates.com/image/i493578.jpg",
  "the sleeping tsukumo": "https://cdn.mangaupdates.com/image/i371904.jpg",
  "coffee master": "https://cdn.mangaupdates.com/image/i246064.jpg",
  "bistro pas mal": "https://cdn.mangaupdates.com/image/i187858.jpg",
  "cactus girl": "https://cdn.mangaupdates.com/image/i349815.jpg",
  "cherry": "https://cdn.mangaupdates.com/image/i118565.jpg",
  "evening twilight": "https://cdn.mangaupdates.com/image/i245465.jpg",
  "samurai 8 - the tale of hachimaru": "https://cdn.mangaupdates.com/image/i315507.jpg",
  "detektif conan: wild police story": "https://cdn.mangaupdates.com/image/i327777.png",
  "the summer hikaru died": "https://cdn.mangaupdates.com/image/i507834.jpg",
  "alice in borderland retry": "https://cdn.mangaupdates.com/image/i337042.jpg",
  "naruto: konoha's story - the steam ninja scrolls": "https://cdn.mangaupdates.com/image/i245536.jpg",
  "a spirit of the sun": "https://cdn.mangaupdates.com/image/i251337.png",
  "master of sea": "https://cdn.mangaupdates.com/image/i295466.jpg",
  "montage": "https://cdn.mangaupdates.com/image/i22478.jpg",
  "bocchi the rock!": "https://cdn.mangaupdates.com/image/i508172.jpg",
  "bounders": "https://cdn.mangaupdates.com/image/i468344.jpg",
  "i've been killing slimes for 300 years and maxed out my level": "https://cdn.mangaupdates.com/image/i534506.jpg",
  "ajin: demi human": "https://cdn.mangaupdates.com/image/i528198.jpg",
  "misteri di balik jeruji": "https://cdn.mangaupdates.com/image/i88457.jpg",
  "love under the blue sky": "https://cdn.mangaupdates.com/image/i304344.jpg",
  "line": "https://cdn.mangaupdates.com/image/i5325.jpg",
  "dream scape": "https://cdn.mangaupdates.com/image/i24395.jpg",
  "high jump!": "https://cdn.mangaupdates.com/image/i231759.jpg",
  "clematica": "https://cdn.mangaupdates.com/image/i303050.jpg",
  "dragon knight": "https://cdn.mangaupdates.com/image/i92894.png",
  "moonlight spice": "https://cdn.mangaupdates.com/image/i495281.jpg",
  "hakamada piano": "https://cdn.mangaupdates.com/image/i19948.jpg",
  "clock clock": "https://cdn.mangaupdates.com/image/i73636.jpg",
  "tsubame and the sweet song of the sea": "https://cdn.mangaupdates.com/image/i163212.jpg",
  "llll": "https://cdn.mangaupdates.com/image/i153461.jpg",
  "today's curry!": "https://cdn.mangaupdates.com/image/i127196.png",
  "happy dining table": "https://cdn.mangaupdates.com/image/i19489.jpg",
  "toko and the flower garden": "https://cdn.mangaupdates.com/image/i173390.jpg",
  "garden of the fairies": "https://cdn.mangaupdates.com/image/i288933.jpg",
  "the complex": "https://cdn.mangaupdates.com/image/i178492.jpg",
  "to you of earth born": "https://cdn.mangaupdates.com/image/i357725.jpg",
  "ibu, satu yang paling berharga": "https://cdn.mangaupdates.com/image/i32093.jpg",
  "escape express": "https://cdn.mangaupdates.com/image/i47730.jpg",
  "golden memory": "https://cdn.mangaupdates.com/image/i30236.jpg",
  "another september": "https://cdn.mangaupdates.com/image/i30237.jpg",
  "morinonaka bookstore": "https://cdn.mangaupdates.com/image/i482022.png",
  "the last episode": "https://cdn.mangaupdates.com/image/i221671.jpg",
  "bintang kematian": "https://cdn.mangaupdates.com/image/i87002.jpg",
  "alone": "https://cdn.mangaupdates.com/image/i245733.png",
  "the swan robe": "https://cdn.mangaupdates.com/image/i77901.png",
  "boys from a bonsai store": "https://cdn.mangaupdates.com/image/i239717.png",
  "melancholic": "https://cdn.mangaupdates.com/image/i101510.png",
  "confession": "https://cdn.mangaupdates.com/image/i153945.png",
  "sayonara papa": "https://cdn.mangaupdates.com/image/i48580.jpg",
  "platonic form": "https://cdn.mangaupdates.com/image/i76068.jpg",
  "the way of cat": "https://cdn.mangaupdates.com/image/i425872.png",
  "meat q family": "https://cdn.mangaupdates.com/image/i61007.jpg",
  "the cat's beautiful gift": "https://cdn.mangaupdates.com/image/i312300.jpg",
  "manekineko real estate": "https://cdn.mangaupdates.com/image/i163194.jpg",
  "your dark wings": "https://cdn.mangaupdates.com/image/i390062.jpg",
  "your white wings": "https://cdn.mangaupdates.com/image/i21184.jpg",
  "world of dreams": "https://cdn.mangaupdates.com/image/i527068.jpg",
  "aqua planet chronicle": "https://cdn.mangaupdates.com/image/i227139.jpg",
  "aqua planet chronicle after": "https://cdn.mangaupdates.com/image/i227139.jpg",
  "aqua planet around": "https://cdn.mangaupdates.com/image/i227139.jpg",
  "aqua planet jade": "https://cdn.mangaupdates.com/image/i227139.jpg",
  "your long hair in the wind": "https://cdn.mangaupdates.com/image/i300141.jpg",
  "unconditional love": "https://cdn.mangaupdates.com/image/i165871.jpg",
  "ikitai i want to live": "https://cdn.mangaupdates.com/image/i44578.jpg",
  "whisper voices": "https://cdn.mangaupdates.com/image/i117951.png",
  "witch in the attic": "https://cdn.mangaupdates.com/image/i350880.png",
  "look back": "https://cdn.mangaupdates.com/image/i158363.jpg",
  "forest of the fireflies": "https://cdn.mangaupdates.com/image/i512866.jpg",
  "1 or w": "https://cdn.mangaupdates.com/image/i537003.jpg",
  "our summer holiday": "https://cdn.mangaupdates.com/image/i293440.jpg",
  "lonely people": "https://cdn.mangaupdates.com/image/i495286.jpg",
  "zero x zero memories": "https://cdn.mangaupdates.com/image/i405449.jpg",
  "magical kiss": "https://cdn.mangaupdates.com/image/i466982.jpg",
  "the ninth cat": "https://cdn.mangaupdates.com/image/i88464.png",
  "black museum spingald": "https://cdn.mangaupdates.com/image/i530214.jpg",
  "the garden of words": "https://cdn.mangaupdates.com/image/i295849.jpg",
  "marie antoinette - the youth of a queen": "https://cdn.mangaupdates.com/image/i427143.png",
  "judge": "https://cdn.mangaupdates.com/image/i221337.jpg",
  "your name": "https://cdn.mangaupdates.com/image/i114349.png",
  "tokyo revengers character book: heaven & earth": "https://cdn.mangaupdates.com/image/i514231.png",
  "horimiya - a piece of memories special edition": "https://cdn.mangaupdates.com/image/i424571.png",
  "bestiarius": "https://cdn.mangaupdates.com/image/i286166.jpg",
  "kimun kamui": "https://cdn.mangaupdates.com/image/i43759.gif",
  "piano hutan": "https://cdn.mangaupdates.com/image/i420568.jpg",
  "good morning, little briar rose": "https://cdn.mangaupdates.com/image/i401837.jpg",
  "piece": "https://cdn.mangaupdates.com/image/i484422.jpg",
  "animal kingdom": "https://cdn.mangaupdates.com/image/i179545.jpg",
  "zero gravity girl": "https://cdn.mangaupdates.com/image/i255415.png",
  "magi: the labyrinth of magic": "https://cdn.mangaupdates.com/image/i174977.jpg",
  "gurren lagann": "https://cdn.mangaupdates.com/image/i526717.jpg",
  "puella magi madoka magica the movie rebellion story": "https://cdn.mangaupdates.com/image/i341346.png",
  "the scissor woman": "https://cdn.mangaupdates.com/image/i415544.jpg",
  "hanako sepulang sekolah": "https://cdn.mangaupdates.com/image/i470948.jpg",
  "5 cm per second": "https://cdn.mangaupdates.com/image/i406078.jpg",
  "goodbye, eri": "https://cdn.mangaupdates.com/image/i527501.jpg",
  "emma": "https://cdn.mangaupdates.com/image/i227786.jpg",
  "wind breaker": "https://cdn.mangaupdates.com/image/i511124.jpg",
  "hero tales": "https://cdn.mangaupdates.com/image/i134431.jpg",
  "animal sense": "https://cdn.mangaupdates.com/image/i348777.png",
  "i'm home": "https://cdn.mangaupdates.com/image/i200142.jpg",
  "detective school q": "https://cdn.mangaupdates.com/image/i282739.png",
  "arms": "https://cdn.mangaupdates.com/image/i207729.jpg",
  "kunimitsu": "https://cdn.mangaupdates.com/image/i275875.jpg",
  "doubt": "https://cdn.mangaupdates.com/image/i381259.jpg",
  "ouroboros": "https://cdn.mangaupdates.com/image/i425030.jpg",
  "kenji premium": "https://cdn.mangaupdates.com/image/i226962.jpg",
  "cage of eden": "https://cdn.mangaupdates.com/image/i152727.jpg",
  "cross game": "https://cdn.mangaupdates.com/image/i293435.jpg",
  "pandemic": "https://cdn.mangaupdates.com/image/i121870.png",
  "d-live!!": "https://cdn.mangaupdates.com/image/i115391.jpg",
  "daikichi's salesmanship": "https://cdn.mangaupdates.com/image/i273639.jpg",
  "fullmetal alchemist (premium)": "https://cdn.mangaupdates.com/image/i513279.jpg",
  "fullmetal alchemist": "https://cdn.mangaupdates.com/image/i513279.jpg",
  "chocolat": "https://cdn.mangaupdates.com/image/i114633.jpg",
  "buddha": "https://cdn.mangaupdates.com/image/i120402.png",
  "so i'm a spider, so what?": "https://cdn.mangaupdates.com/image/i515839.jpg",
  "detektif conan zero's tea time": "https://cdn.mangaupdates.com/image/i161396.jpg",
  "jujutsu kaisen 0": "https://cdn.mangaupdates.com/image/i316618.png",
  "hikaru's go": "https://cdn.mangaupdates.com/image/i537408.jpg",
  "restore garage 251": "https://cdn.mangaupdates.com/image/i449728.jpg",
  "firefighter daigo": "https://cdn.mangaupdates.com/image/i467994.jpg",
  "gto great teacher onizuka": "https://cdn.mangaupdates.com/image/i270861.png",
  "gto shonan junai gumi": "https://cdn.mangaupdates.com/image/i98961.jpg",
  "gto shonan 14 days": "https://cdn.mangaupdates.com/image/i269319.png",
  "the black swindler": "https://cdn.mangaupdates.com/image/i211140.jpg",
  "mr. fullswing": "https://cdn.mangaupdates.com/image/i321263.jpg",
  "silver spoon": "https://cdn.mangaupdates.com/image/i524469.jpg",
  "rainbow days": "https://cdn.mangaupdates.com/image/i519403.jpg",
  "blue spring ride": "https://cdn.mangaupdates.com/image/i426077.png",
  "night patrol teacher": "https://cdn.mangaupdates.com/image/i313555.png",
  "pandora hearts": "https://cdn.mangaupdates.com/image/i216602.png",
  "rising sun": "https://cdn.mangaupdates.com/image/i17449.gif",
  "fairy tail 100 years quest": "https://cdn.mangaupdates.com/image/i520523.jpg",
  "re: zero - starting life in another world: the frozen bond": "https://cdn.mangaupdates.com/image/i356852.jpg",
  "yomi no tsugai: pair of the underworld": "https://cdn.mangaupdates.com/image/i312257.png",
  "mieruko-chan: the girl that sees": "https://cdn.mangaupdates.com/image/i325537.jpg",
  "dandadan": "https://cdn.mangaupdates.com/image/i536675.jpg",
  "life": "https://cdn.mangaupdates.com/image/i453397.jpg",
  "rooster fighter": "https://cdn.mangaupdates.com/image/i529659.jpg",
  "alive: the final evolution": "https://cdn.mangaupdates.com/image/i530672.jpg",
  "a spirit of the sun: founding of the nation": "https://cdn.mangaupdates.com/image/i251338.png",
  "hanako si arwah penasaran 0": "https://cdn.mangaupdates.com/image/i526740.jpg",
  "sora!": "https://cdn.mangaupdates.com/image/i304354.jpg",
  "the ice guy and his cool female colleague": "https://cdn.mangaupdates.com/image/i537719.jpg",
  "hitotsubana: the cursed flower": "https://cdn.mangaupdates.com/image/i498574.jpg",
  "yugo the negotiator": "https://cdn.mangaupdates.com/image/i117599.jpg",
  "yugo the negotiator: side story": "https://cdn.mangaupdates.com/image/i415416.jpg",
  "jepang tenggelam": "https://cdn.mangaupdates.com/image/i213282.png",
  "strobe edge": "https://cdn.mangaupdates.com/image/i223625.jpg",
  "brothers": "https://cdn.mangaupdates.com/image/i113978.jpg",
  "letters from heaven": "https://cdn.mangaupdates.com/image/i271276.jpg",
  "showa man": "https://cdn.mangaupdates.com/image/i23008.jpg",
  "third #4": "https://cdn.mangaupdates.com/image/i258816.jpg",
  "aoyama gosho short stories": "https://cdn.mangaupdates.com/image/i43279.jpg",
  "air gear": "https://cdn.mangaupdates.com/image/i532847.jpg",
  "zom 100: bucket list of the dead": "https://cdn.mangaupdates.com/image/i535069.jpg",
  "fairy tail city hero": "https://cdn.mangaupdates.com/image/i307821.jpg",
  "fairy tail happy adventure": "https://cdn.mangaupdates.com/image/i93686.png",
  "re: zero - starting life in another world - chapter 1: a day in the capital": "https://cdn.mangaupdates.com/image/i133282.jpg",
  "love after world domination": "https://cdn.mangaupdates.com/image/i424623.png",
  "bono bono": "https://cdn.mangaupdates.com/image/i254037.jpg",
  "bono-chan": "https://cdn.mangaupdates.com/image/i278797.jpg",
  "came the mirror": "https://cdn.mangaupdates.com/image/i508806.jpg",
  "change the world – bloodthirsty killer from today": "https://cdn.mangaupdates.com/image/i404537.jpg",
  "chitose is in ramune bottle": "https://cdn.mangaupdates.com/image/i479490.jpg",
  "club activities? so what!": "https://cdn.mangaupdates.com/image/i259786.jpg",
  "gyoro si kelinci": "https://cdn.mangaupdates.com/image/i279839.jpg",
  "gyoro si kelinci - young": "https://cdn.mangaupdates.com/image/i279839.jpg",
  "in the center of the world's end": "https://cdn.mangaupdates.com/image/i438000.jpg",
  "kindaichi 30th anniversary series": "https://cdn.mangaupdates.com/image/i415818.jpg",
  "mashima hero's": "https://cdn.mangaupdates.com/image/i316988.png",
  "mutsunohana exodus": "https://cdn.mangaupdates.com/image/i231953.jpg",
  "the cold sato is only sweet to me": "https://cdn.mangaupdates.com/image/i518654.jpg",
  "the witch & dinner": "https://cdn.mangaupdates.com/image/i449314.jpg",
  "wanted (terbit ulang)": "https://cdn.mangaupdates.com/image/i112341.png",
  "wanted": "https://cdn.mangaupdates.com/image/i112341.png",
  "we start from the night": "https://cdn.mangaupdates.com/image/i393172.jpg",
  "yashahime: princess half demon": "https://cdn.mangaupdates.com/image/i527635.jpg",
  "yoshizawa-kun": "https://cdn.mangaupdates.com/image/i507336.jpg",
  "diorama toy box": "https://cdn.mangaupdates.com/image/i203794.jpg",
  "babysitter gin": "https://cdn.mangaupdates.com/image/i131273.jpg",
  "new black swindler": "https://cdn.mangaupdates.com/image/i155122.jpg",
  "border": "https://cdn.mangaupdates.com/image/i176859.jpg",
  "fly, daddy, fly": "https://cdn.mangaupdates.com/image/i156649.png",
  "dr. koto": "https://cdn.mangaupdates.com/image/i90716.jpg",
  "dr. koto cerita spesial: anak-anak pulau": "https://cdn.mangaupdates.com/image/i121103.png",
  "touhou: silent sinner in blue": "https://cdn.mangaupdates.com/image/i176664.jpg",
  "team medical dragon": "https://cdn.mangaupdates.com/image/i161556.jpg",
  "pokemon the movie: genesect and the legend awakened": "https://cdn.mangaupdates.com/image/i113112.png",
  "pokemon the movie: the power of us zeraora's story": "https://cdn.mangaupdates.com/image/i285070.png",
  "yokohama shopping blog": "https://cdn.mangaupdates.com/image/i457258.jpg",
  "blade of immortal": "https://cdn.mangaupdates.com/image/i444962.jpg",
  "phantom of battleship yamato": "https://cdn.mangaupdates.com/image/i57058.jpg",
  "fairy tail zero": "https://cdn.mangaupdates.com/image/i534719.jpg",
  "pluto": "https://cdn.mangaupdates.com/image/i425031.jpg",
  "mokke": "https://cdn.mangaupdates.com/image/i454714.jpg",
  "zipang": "https://cdn.mangaupdates.com/image/i312900.png",
  "basara": "https://cdn.mangaupdates.com/image/i473086.png",
  "eyeshield 21": "https://cdn.mangaupdates.com/image/i259528.jpg",
  "iliad": "https://cdn.mangaupdates.com/image/i200838.jpg",
  "x": "https://cdn.mangaupdates.com/image/i313948.png",
  "blame": "https://cdn.mangaupdates.com/image/i493560.jpg",
  "noise": "https://cdn.mangaupdates.com/image/i290932.jpg",
  "solanin": "https://cdn.mangaupdates.com/image/i271077.png",
  "saike's repeated days": "https://cdn.mangaupdates.com/image/i285990.jpg",
  "battle game in 5 seconds": "https://cdn.mangaupdates.com/image/i530995.jpg",
  "friends game": "https://cdn.mangaupdates.com/image/i471257.jpg",
  "brother for rent": "https://cdn.mangaupdates.com/image/i527458.jpg",
  "i sold my life for ten thousand yen per year": "https://cdn.mangaupdates.com/image/i493252.jpg",
  "wolf children ame and yuki": "https://cdn.mangaupdates.com/image/i359213.jpg",
  "hitung mundur perpisahanku denganmu": "https://cdn.mangaupdates.com/image/i487955.jpg",
  "the count of monte cristo": "https://cdn.mangaupdates.com/image/i275448.jpg",
  "i saw the same dream again": "https://cdn.mangaupdates.com/image/i458520.jpg",
  "daily life of high school boys": "https://cdn.mangaupdates.com/image/i530413.jpg",
  "takopi's original sins": "https://cdn.mangaupdates.com/image/i525251.jpg",
  "the wedding eve": "https://cdn.mangaupdates.com/image/i141297.png",
  "au revoir, sorcier": "https://cdn.mangaupdates.com/image/i490558.jpg",
  "the inn of lost things": "https://cdn.mangaupdates.com/image/i410598.jpg",
  "terima kasih mama": "https://cdn.mangaupdates.com/image/i119958.png",
  "hal": "https://cdn.mangaupdates.com/image/i399854.jpg",
  "100 days left!!": "https://cdn.mangaupdates.com/image/i353571.jpg",
  "uzumaki": "https://cdn.mangaupdates.com/image/i314977.png",
  "wonderland": "https://cdn.mangaupdates.com/image/i314257.png",
  "the fugitive lawyer makoto narita": "https://cdn.mangaupdates.com/image/i114250.png",
  "rocket man": "https://cdn.mangaupdates.com/image/i217337.png",
  "life existence": "https://cdn.mangaupdates.com/image/i314719.png",
  "the accidents": "https://cdn.mangaupdates.com/image/i127791.png",
  "all you need is kill": "https://cdn.mangaupdates.com/image/i191971.jpg",
  "anohana - the flower we saw that day": "https://cdn.mangaupdates.com/image/i149698.jpg",
  "girl officer hinata": "https://cdn.mangaupdates.com/image/i204953.jpg",
  "love & warship": "https://cdn.mangaupdates.com/image/i494165.jpg",
  "million rooms labyrinth": "https://cdn.mangaupdates.com/image/i534386.jpg",
  "interstellars bridge": "https://cdn.mangaupdates.com/image/i286360.jpg",
  "the new fugitive lawyer makoto narita": "https://cdn.mangaupdates.com/image/i114250.png",
  "calling the death": "https://cdn.mangaupdates.com/image/i269102.jpg",
  "dad, chibi is gone": "https://cdn.mangaupdates.com/image/i369168.jpg",
  "come and find me!": "https://cdn.mangaupdates.com/image/i209560.jpg",
  "the secret case of s.h.": "https://cdn.mangaupdates.com/image/i311688.png",
  "1 litre of tears": "https://cdn.mangaupdates.com/image/i34831.jpg",
  "mail girlfriend": "https://cdn.mangaupdates.com/image/i262029.png",
  "the place between o&k": "https://cdn.mangaupdates.com/image/i138314.png",
  "i'll leave you two alone": "https://cdn.mangaupdates.com/image/i36712.jpg",
  "ghost hunt": "https://cdn.mangaupdates.com/image/i348555.png",
  "midori's days": "https://cdn.mangaupdates.com/image/i372664.jpg",
  "moment by moment": "https://cdn.mangaupdates.com/image/i225281.png",
  "gisele alain": "https://cdn.mangaupdates.com/image/i424588.png",
  "bus for spring": "https://cdn.mangaupdates.com/image/i150900.png",
  "les miserables": "https://cdn.mangaupdates.com/image/i91132.jpg",
  "ill boy & ill girl": "https://cdn.mangaupdates.com/image/i314155.png",
  "37,5°c tears": "https://cdn.mangaupdates.com/image/i499240.jpg",
  "love visual angulation phenomenon": "https://cdn.mangaupdates.com/image/i141944.png",
  "jekyll & hyde and the citizen judges": "https://cdn.mangaupdates.com/image/i230594.png",
  "miss otomurai of the funeral service": "https://cdn.mangaupdates.com/image/i279932.jpg",
  "ichiro's ghost stories": "https://cdn.mangaupdates.com/image/i194860.jpg",
  "wolf's sanctuary": "https://cdn.mangaupdates.com/image/i214307.png",
  "juliet's eggs": "https://cdn.mangaupdates.com/image/i152784.png",
  "burning pen": "https://cdn.mangaupdates.com/image/i89042.jpg",
  "berna & garland": "https://cdn.mangaupdates.com/image/i32009.jpg",
  "d's devil king": "https://cdn.mangaupdates.com/image/i218675.png",
  "fate/grand order: turas realta": "https://cdn.mangaupdates.com/image/i525851.jpg",
  "juliet of the boarding school": "https://cdn.mangaupdates.com/image/i533116.jpg",
  "the world god only knows": "https://cdn.mangaupdates.com/image/i218406.jpg",
  "the world god only knows: on the train + pilot films": "https://cdn.mangaupdates.com/image/i206632.jpg",
  "death's notice": "https://cdn.mangaupdates.com/image/i329228.jpg",
  "dunia mimpi": "https://cdn.mangaupdates.com/image/i206902.jpg",
  "tista": "https://cdn.mangaupdates.com/image/i114375.png",
  "brutal : confession of a homicide investigator": "https://cdn.mangaupdates.com/image/i386777.png",
  "detective these days": "https://cdn.mangaupdates.com/image/i500233.jpg",
  "paman dari dunia lain": "https://cdn.mangaupdates.com/image/i536759.jpg",
  "otherworldly izakaya nobu": "https://cdn.mangaupdates.com/image/i507823.jpg",
  "farming life in another world": "https://cdn.mangaupdates.com/image/i527826.jpg",
  "black jack bind-up edition": "https://cdn.mangaupdates.com/image/i399368.png",
  "20th century boys the complete edition": "https://cdn.mangaupdates.com/image/i86660.png",
  "girls last tour": "https://cdn.mangaupdates.com/image/i527979.jpg",
  "shangri-la frontier": "https://cdn.mangaupdates.com/image/i529658.jpg",
  "kindaichi case files: takato's side": "https://cdn.mangaupdates.com/image/i194913.jpg",
  "yoshi no zuikara - bagai katak dalam tempurung": "https://cdn.mangaupdates.com/image/i88531.png",
  "ptsd radio": "https://cdn.mangaupdates.com/image/i275768.png",
  "sasuke`s story - the uchiha and the heavenly stardust": "https://cdn.mangaupdates.com/image/i164119.png",
  "sweetness & lightning": "https://cdn.mangaupdates.com/image/i534276.jpg",
  "kindaichi r": "https://cdn.mangaupdates.com/image/i266969.png",
  "girls und panzer little army ii": "https://cdn.mangaupdates.com/image/i315215.png",
  "bloody monday": "https://cdn.mangaupdates.com/image/i523198.jpg",
  "bloody monday season 2 pandora's box": "https://cdn.mangaupdates.com/image/i165842.jpg",
  "bloody monday last season": "https://cdn.mangaupdates.com/image/i171747.jpg",
  "whistle!": "https://cdn.mangaupdates.com/image/i314326.png",
  "the hunting of the snark": "https://cdn.mangaupdates.com/image/i489729.jpg",
  "burning hell": "https://cdn.mangaupdates.com/image/i314888.png",
  "factory z": "https://cdn.mangaupdates.com/image/i306460.jpg",
  "trafficker": "https://cdn.mangaupdates.com/image/i286065.png",
  "magic kaito": "https://cdn.mangaupdates.com/image/i284522.jpg",
  "dragon ball - that time i got reincarnated as yamcha": "https://cdn.mangaupdates.com/image/i527276.jpg",
  "sunset on third street": "https://cdn.mangaupdates.com/image/i517022.jpg",
  "azumanga daioh": "https://cdn.mangaupdates.com/image/i313438.png",
  "the sluggish tanaka": "https://cdn.mangaupdates.com/image/i380779.jpg",
  "resident evil marhawa desire": "https://cdn.mangaupdates.com/image/i171013.jpg",
  "highschool of the dead": "https://cdn.mangaupdates.com/image/i524249.jpg",
  "kindaichi 20th anniversary": "https://cdn.mangaupdates.com/image/i508762.jpg",
  "q.e.d.": "https://cdn.mangaupdates.com/image/i293958.png",
  "me is not me bind-up edition": "https://cdn.mangaupdates.com/image/i423755.png",
  "one piece 500 quiz book - get or lost challenger wanted": "https://cdn.mangaupdates.com/image/i355747.jpg",
  "one piece doors!": "https://cdn.mangaupdates.com/image/i531056.jpg",
  "record of ragnarok - the legend of lu bu": "https://cdn.mangaupdates.com/image/i467185.jpg",
  "stand by me doraemon": "https://cdn.mangaupdates.com/image/i36466.jpg",
  "fragments of horror": "https://cdn.mangaupdates.com/image/i317126.png",
  "ito junji compilation 1: tomie part 1": "https://cdn.mangaupdates.com/image/i328815.png",
  "ito junji compilation 2: tomie part 2": "https://cdn.mangaupdates.com/image/i453298.png",
  "ito junji compilation 3: souichi's convenient curses": "https://cdn.mangaupdates.com/image/i314447.png",
  "ito junji compilation 4: lovesickness": "https://cdn.mangaupdates.com/image/i242832.jpg",
  "ito junji compilation 5: a deserter in the house": "https://cdn.mangaupdates.com/image/i95518.png",
  "ito junji compilation 6: the back alley": "https://cdn.mangaupdates.com/image/i320349.jpg",
  "gyo complete edition - 2 in 1": "https://cdn.mangaupdates.com/image/i466208.jpg",
  "hellstar remina": "https://cdn.mangaupdates.com/image/i303076.jpg",
  "ito junji - best of best short story collection": "https://cdn.mangaupdates.com/image/i287913.jpg",
  "ito junji's selected collection - shiver": "https://cdn.mangaupdates.com/image/i314332.png",
  "junji ito's cat diary yon and mu": "https://cdn.mangaupdates.com/image/i117500.jpg",
  "dissolving classroom": "https://cdn.mangaupdates.com/image/i220191.jpg",
  "black paradox": "https://cdn.mangaupdates.com/image/i303078.jpg",
  "kagurabachi": "https://cdn.mangaupdates.com/image/i536550.jpg",
  "tatsuki fujimoto before chainsaw man 17-21": "https://cdn.mangaupdates.com/image/i377772.jpg",
  "teka-teki rumah aneh - hen na ie": "https://cdn.mangaupdates.com/image/i510209.jpg",
  "wotakoi: love is hard for otaku - comic anthology": "https://cdn.mangaupdates.com/image/i481800.jpg",
  "ruri dragon": "https://cdn.mangaupdates.com/image/i527478.jpg",
  "kaiju no. 8: b side": "https://cdn.mangaupdates.com/image/i537050.jpg",
  "heroes": "https://cdn.mangaupdates.com/image/i4572.jpg",
  "first love": "https://cdn.mangaupdates.com/image/i171081.jpg",
  "tutti!": "https://cdn.mangaupdates.com/image/i222658.png",
  "strike the youth": "https://cdn.mangaupdates.com/image/i527786.jpg",
  "the mysterious book of sorcery": "https://cdn.mangaupdates.com/image/i315430.png",
  "shin masked rider - shocker side": "https://cdn.mangaupdates.com/image/i503711.jpg",
  "untuk dirimu yang baru": "https://cdn.mangaupdates.com/image/i480974.jpg",
  "gokurakugai": "https://cdn.mangaupdates.com/image/i534735.jpg",
  "blue period": "https://cdn.mangaupdates.com/image/i307028.jpg",
  "samurai x - another story": "https://cdn.mangaupdates.com/image/i467269.jpg",
  "gachiakuta": "https://cdn.mangaupdates.com/image/i531059.jpg",
  "i want to eat your pancreass bind-up": "https://cdn.mangaupdates.com/image/i488103.jpg",
  "100 pacar yang sangat, sangat, sangat, sangat, sangat, sangat, mencintaimu": "https://cdn.mangaupdates.com/image/i323543.jpg",
  "the bird of fate": "https://cdn.mangaupdates.com/image/i129514.jpg",
  "holoearth chronicles side: e - kisah fantasi yamato": "https://cdn.mangaupdates.com/image/i527504.jpg",
  "kaijin fugeki": "https://cdn.mangaupdates.com/image/i536504.jpg",
  "bamboo blade": "https://cdn.mangaupdates.com/image/i123377.png",
  "atelier of witch hat": "https://cdn.mangaupdates.com/image/i535883.jpg",
  "harlem beat (bunkoban)": "https://cdn.mangaupdates.com/image/i43576.gif",
  "harlem beat": "https://cdn.mangaupdates.com/image/i43576.gif",
  "sailor moon (deluxe)": "https://cdn.mangaupdates.com/image/i348762.png",
  "sailor moon": "https://cdn.mangaupdates.com/image/i348762.png",
  "inuyasha (premium)": "https://cdn.mangaupdates.com/image/i524488.jpg",
  "inuyasha": "https://cdn.mangaupdates.com/image/i524488.jpg",
  "book of horror": "https://cdn.mangaupdates.com/image/i139202.png",
  "king's game: origin": "https://cdn.mangaupdates.com/image/i402304.jpg",
  "orange": "https://cdn.mangaupdates.com/image/i37240.jpg",
  "soramiya club": "https://cdn.mangaupdates.com/image/i533495.jpg",
  "shibatora": "https://cdn.mangaupdates.com/image/i159475.jpg",
  "tatsuki fujimoto before chainsaw man 22-26": "https://cdn.mangaupdates.com/image/i377772.jpg",
  "iris zero": "https://cdn.mangaupdates.com/image/i285841.png",
  "captain tsubasa road to 2002": "https://cdn.mangaupdates.com/image/i125335.jpg",
  "pembunuhan di rumah dekagon": "https://cdn.mangaupdates.com/image/i386386.jpg",
  "dear boys": "https://cdn.mangaupdates.com/image/i484248.jpg",
  "break shot (deluxe)": "https://cdn.mangaupdates.com/image/i201681.png",
  "break shot": "https://cdn.mangaupdates.com/image/i201681.png",
  "captain tsubasa world youth version": "https://cdn.mangaupdates.com/image/i125334.jpg",
  "hell girl return": "https://cdn.mangaupdates.com/image/i134125.jpg",
  "bono bono s": "https://cdn.mangaupdates.com/image/i254037.jpg",
  "the secret of girls": "https://cdn.mangaupdates.com/image/i223463.jpg",
  "antique fuga": "https://cdn.mangaupdates.com/image/i496252.jpg",
  "parasite in love": "https://cdn.mangaupdates.com/image/i331605.jpg",
  "i came to be married to the demon (bind up)": "https://cdn.mangaupdates.com/image/i363597.jpg",
  "i came to be married to the demon": "https://cdn.mangaupdates.com/image/i363597.jpg",
  "hotel la vie en rose": "https://cdn.mangaupdates.com/image/i157505.jpg",
  "lots of love": "https://cdn.mangaupdates.com/image/i20496.gif",
  "black clover 16.5": "https://cdn.mangaupdates.com/image/i534037.jpg",
  "h2": "https://cdn.mangaupdates.com/image/i161886.jpg",
  "new kung fu boy": "https://cdn.mangaupdates.com/image/i451793.jpg",
  "saint seiya the lost canvas": "https://cdn.mangaupdates.com/image/i249163.png",
  "to be continued tomorrow": "https://cdn.mangaupdates.com/image/i156028.png",
  "the tale of dororo and hyakkimaru": "https://cdn.mangaupdates.com/image/i511117.jpg",
  "tokyo aliens": "https://cdn.mangaupdates.com/image/i533798.jpg",
  "doraemon (terbit ulang)": "https://cdn.mangaupdates.com/image/i204707.jpg",
  "doraemon": "https://cdn.mangaupdates.com/image/i204707.jpg",
  "yona, the girl standing in the blush of dawn": "https://cdn.mangaupdates.com/image/i399502.jpg",
  "nyankees": "https://cdn.mangaupdates.com/image/i308367.png",
  "bungo stray dogs - beast": "https://cdn.mangaupdates.com/image/i434108.png",
  "law of ueki": "https://cdn.mangaupdates.com/image/i524494.jpg",
  "law of ueki plus": "https://cdn.mangaupdates.com/image/i132858.jpg",
  "shoot legend of new age": "https://cdn.mangaupdates.com/image/i382093.jpg",
  "angel heart": "https://cdn.mangaupdates.com/image/i228658.jpg",
  "masked rider spirits": "https://cdn.mangaupdates.com/image/i60292.jpg",
  "mär": "https://cdn.mangaupdates.com/image/i496796.png",
  "mär omega": "https://cdn.mangaupdates.com/image/i278029.png",
  "wistoria: wand and sword": "https://cdn.mangaupdates.com/image/i525669.jpg",
  "who killed the brave?": "https://cdn.mangaupdates.com/image/i291830.jpg",
  "tentang suatu tempat di wilayah kinki": "https://cdn.mangaupdates.com/image/i492948.jpg",
  "koi gurumi": "https://cdn.mangaupdates.com/image/i157519.jpg",
  "versus": "https://cdn.mangaupdates.com/image/i527269.jpg",
  "jigokuraku": "https://cdn.mangaupdates.com/image/i34298.jpg",
  "flame of recca (bunkoban)": "https://cdn.mangaupdates.com/image/i524493.jpg",
  "flame of recca": "https://cdn.mangaupdates.com/image/i524493.jpg",
  "girls und panzer little army": "https://cdn.mangaupdates.com/image/i315217.png",
  "meteodo": "https://cdn.mangaupdates.com/image/i250115.jpg",
  "chocolate magic: classic chocolate - lost story": "https://cdn.mangaupdates.com/image/i83749.jpg",
  "cook x doppo": "https://cdn.mangaupdates.com/image/i189714.jpg",
  "kekkaishi": "https://cdn.mangaupdates.com/image/i320514.jpg",
  "parasyte": "https://cdn.mangaupdates.com/image/i530677.jpg",
  "penyihir hutan kokonoka": "https://cdn.mangaupdates.com/image/i371146.jpg",
  "pokonyan pika-pika": "https://cdn.mangaupdates.com/image/i49054.jpg",
  "raibarong - the immortal doll": "https://cdn.mangaupdates.com/image/i406013.jpg",
  "rixa": "https://cdn.mangaupdates.com/image/i406014.jpg",
  "runaway summer boy": "https://cdn.mangaupdates.com/image/i492960.jpg",
  "the furo siblings": "https://cdn.mangaupdates.com/image/i528401.jpg",
  "akame ga kill!": "https://cdn.mangaupdates.com/image/i529137.jpg",
  "bocchi the rock! side story: kikuri the \"drunk hero\" rock story": "https://cdn.mangaupdates.com/image/i531197.jpg",
  "hunter x hunter": "https://cdn.mangaupdates.com/image/i530450.jpg",
  "seeds of anxiety (3 in 1)": "https://cdn.mangaupdates.com/image/i502888.jpg",
  "seeds of anxiety": "https://cdn.mangaupdates.com/image/i502888.jpg",
  "yuyu hakusho premium": "https://cdn.mangaupdates.com/image/i226962.jpg",
  "is the order a rabbit?": "https://cdn.mangaupdates.com/image/i498917.jpg",
  "in the summer when you die": "https://cdn.mangaupdates.com/image/i278568.jpg",
  "non non biyori": "https://cdn.mangaupdates.com/image/i527082.jpg",
  "golden mosaic": "https://cdn.mangaupdates.com/image/i493414.jpg",
  "re : creators one more": "https://cdn.mangaupdates.com/image/i106967.png",
  "ms. koizumi loves ramen noodles": "https://cdn.mangaupdates.com/image/i527541.jpg",
  "castle town dandelion": "https://cdn.mangaupdates.com/image/i476467.jpg",
  "hidamari sketch": "https://cdn.mangaupdates.com/image/i276771.jpg",
  "hanayamata": "https://cdn.mangaupdates.com/image/i275020.png",
  "dog detective sherdock": "https://cdn.mangaupdates.com/image/i497243.jpg",
  "at night i move": "https://cdn.mangaupdates.com/image/i290097.png",
  "claymore": "https://cdn.mangaupdates.com/image/i526259.jpg",
  "the prince of tennis": "https://cdn.mangaupdates.com/image/i309883.jpg",
  "roulette battler": "https://cdn.mangaupdates.com/image/i201675.png",
  "happy happy clover": "https://cdn.mangaupdates.com/image/i195218.jpg",
  "kariage kun": "https://cdn.mangaupdates.com/image/i260065.jpg",
  "puella magi madoka magica the different story": "https://cdn.mangaupdates.com/image/i341346.png",
  "wizard of oz": "https://cdn.mangaupdates.com/image/i246137.jpg",
  "kindaichi file": "https://cdn.mangaupdates.com/image/i208426.jpg",
  "mystery in cheju island": "https://cdn.mangaupdates.com/image/i424993.jpg",
  "sylphid": "https://cdn.mangaupdates.com/image/i140243.jpg",
  "black cat": "https://cdn.mangaupdates.com/image/i251278.png",
  "the designer's revenge": "https://cdn.mangaupdates.com/image/i192194.jpg",
  "koro sensei quest!": "https://cdn.mangaupdates.com/image/i308363.png",
  "saint seiya episode g": "https://cdn.mangaupdates.com/image/i384850.jpg",
  "my favorite bike": "https://cdn.mangaupdates.com/image/i320002.jpg",
  "bambino secondo": "https://cdn.mangaupdates.com/image/i191223.jpg",
  "topeng kaca": "https://cdn.mangaupdates.com/image/i141276.png",
  "aldnoah.zero 2nd season": "https://cdn.mangaupdates.com/image/i226743.jpg",
  "salon diana": "https://cdn.mangaupdates.com/image/i216343.jpg",
  "chimpui (premium)": "https://cdn.mangaupdates.com/image/i135629.jpg",
  "chimpui": "https://cdn.mangaupdates.com/image/i135629.jpg",
  "café de laylah": "https://cdn.mangaupdates.com/image/i228823.png",
  "mira kuru": "https://cdn.mangaupdates.com/image/i453358.jpg",
  "yu-gi-oh!": "https://cdn.mangaupdates.com/image/i289296.jpg",
  "choujin x": "https://cdn.mangaupdates.com/image/i535341.jpg",
  "medalist": "https://cdn.mangaupdates.com/image/i531753.jpg",
  "blue giant": "https://cdn.mangaupdates.com/image/i372944.jpg",
  "nisekoi: false love": "https://cdn.mangaupdates.com/image/i526261.jpg",
  "dragon ball": "https://cdn.mangaupdates.com/image/i152981.jpg",
  "tentang kita yang bertolak belakang": "https://cdn.mangaupdates.com/image/i477585.jpg",
  "cerita spesial doraemon": "https://cdn.mangaupdates.com/image/i204707.jpg",
  "my friend's little sister has it in for me!": "https://cdn.mangaupdates.com/image/i523883.jpg",
  "you are a four-leaf clover": "https://cdn.mangaupdates.com/image/i51284.png",
  "hear the voice of the dead": "https://cdn.mangaupdates.com/image/i535819.jpg",
  "soloist in a cage": "https://cdn.mangaupdates.com/image/i403173.jpg",
  "shiraken scholar society": "https://cdn.mangaupdates.com/image/i379387.jpg",
  "grand blue dreaming": "https://cdn.mangaupdates.com/image/i526846.jpg",
  "ichi the witch": "https://cdn.mangaupdates.com/image/i529237.jpg",
  "i want to end this love game": "https://cdn.mangaupdates.com/image/i526104.jpg",
  "phantom busters": "https://cdn.mangaupdates.com/image/i523113.jpg",
  "witch watch": "https://cdn.mangaupdates.com/image/i534039.jpg",
  "in the clear moonlit dusk": "https://cdn.mangaupdates.com/image/i511864.jpg",
  "beck": "https://cdn.mangaupdates.com/image/i526716.jpg",
  "doraemon vol. 0": "https://cdn.mangaupdates.com/image/i369985.jpg",
  "scarlet": "https://cdn.mangaupdates.com/image/i164492.png",
  "5 centimeters per second": "https://cdn.mangaupdates.com/image/i343972.jpg",
  "seeds of anxiety +": "https://cdn.mangaupdates.com/image/i502888.jpg",
  "vongola grand prix": "https://cdn.mangaupdates.com/image/i130871.jpg",
  "the shape of voice": "https://cdn.mangaupdates.com/image/i470155.jpg",
  "grim night tales": "https://cdn.mangaupdates.com/image/i534281.jpg",
  "captain tsubasa": "https://cdn.mangaupdates.com/image/i125333.jpg",
  "perjuangan cinta pertama akira momose": "https://cdn.mangaupdates.com/image/i536593.jpg",
  "before dawn and the end of the world": "https://cdn.mangaupdates.com/image/i266308.png",
  "the hitman's fave": "https://cdn.mangaupdates.com/image/i512644.jpg",
  "hell teacher nube": "https://cdn.mangaupdates.com/image/i204469.jpg",
  "zoids: battle story of bio machine zoids": "https://cdn.mangaupdates.com/image/i49925.gif",
  "the real master cooking boy": "https://cdn.mangaupdates.com/image/i287426.jpg",
  "godhand teru": "https://cdn.mangaupdates.com/image/i159115.jpg",
  "vicious horse grooming up!": "https://cdn.mangaupdates.com/image/i211836.jpg",
  "wonder school boy": "https://cdn.mangaupdates.com/image/i110950.png",
  "dan doh!!": "https://cdn.mangaupdates.com/image/i115464.jpg",
  "happy cooking graffiti": "https://cdn.mangaupdates.com/image/i488762.jpg",
  "okinawa": "https://cdn.mangaupdates.com/image/i280932.jpg",
  "doraemon petualangan": "https://cdn.mangaupdates.com/image/i374418.jpg",
  "the call of cthulhu": "https://cdn.mangaupdates.com/image/i387115.png",
  "mushoku tensei: jobless reincarnation": "https://cdn.mangaupdates.com/image/i516050.jpg",
  "lycoris recoil": "https://cdn.mangaupdates.com/image/i537391.jpg",
  "alya sometimes hides her feeling in russian": "https://cdn.mangaupdates.com/image/i537694.jpg",
  "juvenile remix": "https://cdn.mangaupdates.com/image/i216514.png",
  "iroha & aku": "https://cdn.mangaupdates.com/image/i259793.jpg",
  "red river": "https://cdn.mangaupdates.com/image/i453052.jpg",
  "tetsugaku letra": "https://cdn.mangaupdates.com/image/i216213.jpg",
  "eternal sabbath": "https://cdn.mangaupdates.com/image/i153439.png",
  "fight ippo": "https://cdn.mangaupdates.com/image/i458081.jpg",
  "apollon on the slope": "https://cdn.mangaupdates.com/image/i127706.png",
  "girls und panzer": "https://cdn.mangaupdates.com/image/i261425.png",
  "a chef of nobunaga": "https://cdn.mangaupdates.com/image/i508669.jpg",
  "attack on titan lost girls": "https://cdn.mangaupdates.com/image/i371288.jpg",
  "attack on titan no regrets": "https://cdn.mangaupdates.com/image/i507635.jpg",
  "sailor moon short stories": "https://cdn.mangaupdates.com/image/i35813.jpg",
  "sailor v (deluxe)": "https://cdn.mangaupdates.com/image/i453368.jpg",
  "sailor v": "https://cdn.mangaupdates.com/image/i453368.jpg",
  "a meal makes her forgot": "https://cdn.mangaupdates.com/image/i519685.jpg",
  "kuroko's basketball": "https://cdn.mangaupdates.com/image/i210448.jpg",
  "c.m.b": "https://cdn.mangaupdates.com/image/i335242.jpg",
  "dig it": "https://cdn.mangaupdates.com/image/i536428.jpg",
  "one piece episode a": "https://cdn.mangaupdates.com/image/i392252.jpg",
  "bambino": "https://cdn.mangaupdates.com/image/i237669.jpg",
  "hajime is no. 1": "https://cdn.mangaupdates.com/image/i107465.jpg",
  "yakitate!! japan": "https://cdn.mangaupdates.com/image/i158229.jpg",
  "puella magi kazumi magica": "https://cdn.mangaupdates.com/image/i341346.png",
  "black heart star": "https://cdn.mangaupdates.com/image/i177096.jpg",
  "editor editor": "https://cdn.mangaupdates.com/image/i509924.jpg",
  "solo leveling": "https://cdn.mangaupdates.com/image/i515366.jpg",
  "fate grand order: epic of remnant - seven duels of swordmasters": "https://cdn.mangaupdates.com/image/i525930.jpg",
  "a school frozen in time": "https://cdn.mangaupdates.com/image/i362116.jpg",
  "the girl i like forgot her glassess": "https://cdn.mangaupdates.com/image/i474548.jpg",
  "fate/grand order - mortalis: stella": "https://cdn.mangaupdates.com/image/i407881.jpg",
  "fate/apocrypha": "https://cdn.mangaupdates.com/image/i362065.jpg",
  "fate grand order: epic of remnant - heretical salem": "https://cdn.mangaupdates.com/image/i356203.jpg",
  "three days of happiness": "https://cdn.mangaupdates.com/image/i493252.jpg",
  "he doesn't love me, i think": "https://cdn.mangaupdates.com/image/i394761.jpg",
  "kachikachi": "https://cdn.mangaupdates.com/image/i504240.jpg",
  "lofty flower, fall for me": "https://cdn.mangaupdates.com/image/i317971.jpg",
  "highschool fiance": "https://cdn.mangaupdates.com/image/i509586.png",
  "si sok cuek inugami": "https://cdn.mangaupdates.com/image/i280283.jpg",
  "giant killing": "https://cdn.mangaupdates.com/image/i525716.jpg",
  "one piece blue deep characters world": "https://cdn.mangaupdates.com/image/i94630.png",
  "one piece green secret pieces": "https://cdn.mangaupdates.com/image/i94630.png",
  "one piece yellow grand elements": "https://cdn.mangaupdates.com/image/i94630.png",
  "one piece blue grand data file": "https://cdn.mangaupdates.com/image/i94630.png",
  "komikus shojo nozaki anthology": "https://cdn.mangaupdates.com/image/i532361.jpg",
  "handa-kun anthology": "https://cdn.mangaupdates.com/image/i526251.jpg",
  "the black detective": "https://cdn.mangaupdates.com/image/i250726.png",
  "kindergarten wars": "https://cdn.mangaupdates.com/image/i523121.jpg",
  "frieren anthology": "https://cdn.mangaupdates.com/image/i443286.jpg",
  "dead dead demons dedede": "https://cdn.mangaupdates.com/image/i398311.png",
  "master keaton": "https://cdn.mangaupdates.com/image/i387638.jpg",
  "tokkyu": "https://cdn.mangaupdates.com/image/i53027.gif",
  "detektif conan reader's choice": "https://cdn.mangaupdates.com/image/i14068.jpg",
  "detektif conan the movie comics edition: quarter of silence": "https://cdn.mangaupdates.com/image/i524781.jpg",
  "detektif conan the movie comics edition: private eye in the distant sea": "https://cdn.mangaupdates.com/image/i524781.jpg",
  "detektif conan the movie comics edition: countdown to heaven": "https://cdn.mangaupdates.com/image/i524781.jpg",
  "detektif conan the movie comics edition: the lost ship in the sky": "https://cdn.mangaupdates.com/image/i524781.jpg",
  "detektif conan the movie comics edition: the crimson love letters": "https://cdn.mangaupdates.com/image/i524781.jpg",
  "detektif conan the movie comics edition: crossroad in the ancient capital": "https://cdn.mangaupdates.com/image/i268705.jpg",
  "detektif conan the movie comics edition: the raven chaser": "https://cdn.mangaupdates.com/image/i524781.jpg",
  "detektif conan the movie comics edition: the last wizard of the century": "https://cdn.mangaupdates.com/image/i158262.jpg",
  "detektif conan the movie comics edition: dimensional sniper": "https://cdn.mangaupdates.com/image/i524781.jpg",
  "detektif conan the movie comics edition: the bride of halloween": "https://cdn.mangaupdates.com/image/i524781.jpg",
  "detektif conan the movie comics edition: the scarlet bullet": "https://cdn.mangaupdates.com/image/i524781.jpg",
  "detektif conan: shuichi akai selection": "https://cdn.mangaupdates.com/image/i255499.jpg",
  "detektif conan: akai family selection": "https://cdn.mangaupdates.com/image/i255499.jpg",
  "detektif conan: soccer selection": "https://cdn.mangaupdates.com/image/i255499.jpg",
  "detektif conan: fbi selection": "https://cdn.mangaupdates.com/image/i255499.jpg",
  "detektif conan: double face selection": "https://cdn.mangaupdates.com/image/i196294.jpg",
  "detektif conan romantic selection": "https://cdn.mangaupdates.com/image/i225185.png",
  "detektif conan: makoto kyogoku selection": "https://cdn.mangaupdates.com/image/i255499.jpg",
  "detektif conan: toru amuro selection": "https://cdn.mangaupdates.com/image/i255499.jpg",
  "detektif conan dead or alive selection": "https://cdn.mangaupdates.com/image/i434817.jpg",
  "detektif conan: ai haibara selection": "https://cdn.mangaupdates.com/image/i255499.jpg",
  "detektif conan: shinichi kudo selection": "https://cdn.mangaupdates.com/image/i255499.jpg",
  "detektif conan: police academy selection": "https://cdn.mangaupdates.com/image/i255499.jpg",
  "rave master": "https://cdn.mangaupdates.com/image/i350251.jpg",
  "miriam - romantic dream": "https://cdn.mangaupdates.com/image/i51031.jpg",
  "god's life is tough": "https://cdn.mangaupdates.com/image/i455353.png",
  "hitman reborn!": "https://cdn.mangaupdates.com/image/i207532.jpg",
  "i sold my life for ten thousand yen per year (bookpaper)": "https://cdn.mangaupdates.com/image/i493252.jpg",
  "who killed the brave? chapter of prophecy": "https://cdn.mangaupdates.com/image/i291830.jpg",
  "tentang ziarah yang terkutuk": "https://cdn.mangaupdates.com/image/i496132.jpg",
  "kamen rider 913": "https://cdn.mangaupdates.com/image/i102132.jpg",
  "detektif conan secret archives 2 shuichi akai & toru amuro": "https://cdn.mangaupdates.com/image/i387760.jpg",
  "18 eighteen": "https://cdn.mangaupdates.com/image/i343072.jpg",
  "let's eat together": "https://cdn.mangaupdates.com/image/i359946.jpg",
  "ghost fixers": "https://cdn.mangaupdates.com/image/i517865.jpg",
  "nurse aoi": "https://cdn.mangaupdates.com/image/i318613.jpg",
  "nurse aoi those days": "https://cdn.mangaupdates.com/image/i318614.jpg",
  "love, be loved leave, be left": "https://cdn.mangaupdates.com/image/i293307.jpg",
  "red": "https://cdn.mangaupdates.com/image/i296206.jpg",
  "artist acro": "https://cdn.mangaupdates.com/image/i236069.jpg",
  "azur lane queen's orders": "https://cdn.mangaupdates.com/image/i505356.jpg",
  "the eminence in shadow": "https://cdn.mangaupdates.com/image/i522941.jpg",
  "alice academy": "https://cdn.mangaupdates.com/image/i529355.jpg",
  "maria holic": "https://cdn.mangaupdates.com/image/i532420.jpg",
  "riddle of gravity - daydream": "https://cdn.mangaupdates.com/image/i420710.jpg",
  "exposing game": "https://cdn.mangaupdates.com/image/i119963.png",
  "world embryo": "https://cdn.mangaupdates.com/image/i536709.jpg",
  "one piece red grand characters": "https://cdn.mangaupdates.com/image/i94630.png",
  "fire punch": "https://cdn.mangaupdates.com/image/i527509.jpg",
  "tamon's b-side": "https://cdn.mangaupdates.com/image/i521366.jpg",
  "dollhouse": "https://cdn.mangaupdates.com/image/i481111.jpg",
  "learning to love my cat-like classmate": "https://cdn.mangaupdates.com/image/i522335.jpg",
  "your lie in april": "https://cdn.mangaupdates.com/image/i530673.jpg",
  "short program": "https://cdn.mangaupdates.com/image/i78429.jpg",
  "vagabond": "https://cdn.mangaupdates.com/image/i426098.png",
  "namaku miiko - boxset 4 in 1": "https://cdn.mangaupdates.com/image/i401963.png",
  "hope you’re happy, lemon": "https://cdn.mangaupdates.com/image/i522631.jpg",
  "smoking behind the supermarket with you": "https://cdn.mangaupdates.com/image/i533797.jpg",
  "the cute british girl next door and her sister": "https://cdn.mangaupdates.com/image/i124518.png",
  "makeine – heroine yang patah hati terlalu banyak!": "https://cdn.mangaupdates.com/image/i511969.jpg",
  "karada sagashi: another": "https://cdn.mangaupdates.com/image/i523128.jpg",
  "cosmos": "https://cdn.mangaupdates.com/image/i527830.jpg",
  "albus changes the world": "https://cdn.mangaupdates.com/image/i537901.jpg",
  "hidup di dalam bathtub": "https://cdn.mangaupdates.com/image/i444172.png"
};
