window.PRELOADED_COVERS = {
  "fist of the north star": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx31149-TOwqxOlY1Zs0.jpg",
  "city hunter (complete edition)": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30792-62RxEnU7tlDg.png",
  "city hunter": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30792-62RxEnU7tlDg.png",
  "detektif conan premium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx41176-IkOUYyagp3OP.jpg",
  "shaman king": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30050-QMt9D1G9ZZTV.png",
  "black clover": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx114652-b4VxxYpvU8id.png",
  "dragon ball super": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx86508-QSahE7mTFEXl.png",
  "q.e.d. iff": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx94925-IM485Ezl3BzO.jpg",
  "hanako si arwah penasaran (bookpaper)": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx98842-Ji0v423UZ4er.jpg",
  "hanako si arwah penasaran": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx98842-Ji0v423UZ4er.jpg",
  "haikyu! fly high volleyball!": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx181735-xIoXaQmtjkuC.png",
  "tokyo revengers": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx102988-OoVJxQCH6fbR.jpg",
  "teasing master, takagi": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx85533-lrXvNT9iH9sY.jpg",
  "the quintessential quintuplets": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx100230-TA0RQ9d7RVas.jpg",
  "detektif kindaichi 37 tahun": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx102922-mdfHtUAP5hRG.png",
  "moriarty the patriot": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx98544-UzMzrwxRii6p.jpg",
  "dr. slump (bunkoban)": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30796-PFF4n7Y2spz9.png",
  "dr. slump": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30796-PFF4n7Y2spz9.png",
  "mob psycho 100": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx85189-06aXUBq5jwce.jpg",
  "bakemonogatari": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx101311-NOQuXK7eRHDm.jpg",
  "detektif kindaichi premium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30393-1OQNCv5LIsx8.jpg",
  "wotakoi: love is hard for otaku": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx86717-S7z7uizfTfEu.png",
  "futo detective": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx99779-aBsjDVek3hu9.jpg",
  "dead mount death play": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx100868-0xKZvKkdXZyO.jpg",
  "frieren: after the end": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx118586-CXKgWikBFQgS.jpg",
  "sakamoto days": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx125828-p78Z8SflkfmO.jpg",
  "kanojo okarishimasu": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx99943-DX7nDMeqSTk3.png",
  "bungo stray dogs": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx85307-23PaGq5FakEV.png",
  "a couple of cuckoos": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx112024-tz9XJLAlrXgr.jpg",
  "one room of happiness": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx100557-55nghYjyfP4i.jpg",
  "final fantasy: lost stranger": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx102232-nbSn305VsCtg.jpg",
  "fate/strange fake": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx50006-SzwC3M73aM2X.jpg",
  "hibiki: kiat menjadi novelis": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx99040-lOAnqvXBbzvn.jpg",
  "samurai x: hokkaido arc": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx101938-X3B3SG90WlJP.jpg",
  "alice in borderland": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx63031-lE9pKD3cpmVK.jpg",
  "dr. stone": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/b98416-L44f4idEGMAX.jpg",
  "kubo won't let me be invisible": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx112981-lI95vW7wk8Nv.jpg",
  "blood lad": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/92948-9UCXTRWhxaJI.jpg",
  "mashle": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx114960-pivAwNQDdiBa.jpg",
  "gokushufudo - the way of house husband": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx101233-ipG2rYitNxyd.jpg",
  "one week friends": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx73967-5YNYySbjWx5v.jpg",
  "smile at the runway": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx99757-daVTRPuOz1LM.png",
  "the promised neverland": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx87423-gPNtu8QbGped.jpg",
  "the skull starts moving in the dark night": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx180127-EQDdVzUMLGYI.jpg",
  "yotsuba&!": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30104-sUVzNlTWZ5cu.jpg",
  "c.m.b.": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx40318-o6mUl2TBaY0M.jpg",
  "the memorandum of kyoko okitegami": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx86808-H6dWmRBpvJc7.png",
  "my name is a": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx116228-LgcjrEEHO81w.jpg",
  "another": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx54098-NZ21m9i1lZOs.jpg",
  "shiomi-chan": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx97704-pKZqAZKKgPYp.jpg",
  "barefoot gen": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx33281-2NXB8uHRxpI3.png",
  "say hello to black jack": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/b31668-u4LJzRLkpx6s.jpg",
  "sket dance": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx31414-tz6DO9Tns3e0.png",
  "i want to eat your pancreass": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx99609-hfnudDtTT1n5.jpg",
  "record of ragnarok": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx107098-zjO64Bc3Nrm5.jpg",
  "demon slayer: kimetsu no yaiba": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx87216-c9bSNVD10UuD.png",
  "chainsaw man": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx105778-euxXZEIfDY2u.png",
  "hellsing": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx39760-ttrfuONSRq54.png",
  "jujutsu kaisen": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx101517-H3TdM3g5ZUe9.jpg",
  "the apothecary diaries": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx99022-Hh2WdyNgR8HM.jpg",
  "erased": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx69325-17ud19Cg0xIO.jpg",
  "trace: recollections of a forensic researcher": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx104998-LFvSlR3bF2r8.jpg",
  "komikus shojo nozaki": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx59211-ltc4FW9inrms.jpg",
  "aku no hana : kembang jahanam": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx107437-mkW9qJgQkZXA.png",
  "the journey of elaina": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx98741-O0Xcc89Id03h.jpg",
  "my capricorn friend": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx86833-8k7Z6F0L6mGz.jpg",
  "hideout": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/28361.jpg",
  "tokyo ghoul": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx63327-glC9cDxYBja9.png",
  "blue box": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx122342-50btLRhAOhsk.jpg",
  "ragna crimson": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx99065-3LKF0OVyP0To.jpg",
  "kaguya-sama: love is war": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx86635-EdaLQmsn86Fy.png",
  "edens zero": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx101860-mlmDqQ8T4x4j.jpg",
  "spy x family": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx108556-NHjkz0BNJhLx.jpg",
  "re: zero - starting life in another world - chapter 2: a week at the mansion": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx85814-2GgK1VJ8OQwu.jpg",
  "oshi no ko: anak idola": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx117195-r3kf8eF0xkDJ.png",
  "attack on titan before the fall": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx73999-YpiZ2B2lBqYL.jpg",
  "after the rain": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx86639-ox749qrCTq7K.jpg",
  "city hunter rebirth": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx117854-xOTpWnxFpZFe.jpg",
  "tokyo ghoul: re": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx85611-Asb0BNP23NsJ.png",
  "cells at work!": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx86778-yms0DmPwIXu9.jpg",
  "cells at work! black": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx103586-BRlLQ0PbJCRc.jpg",
  "my hero academia": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx97154-F7eF8hnjAPNI.jpg",
  "the king's beast": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx107544-r0fa0H1KDoOD.png",
  "when you wish upon a star": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx92535-s8KL21T7ZNii.jpg",
  "the eternal zero": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx86725-PoZyYPjjJDBA.jpg",
  "just the two of us": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx59981-DsBdu0h390ql.jpg",
  "blue lock": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx106130-yPNeuSu75ey1.jpg",
  "second summer, never see you again": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx102243-E4U3c7hO8nkj.jpg",
  "my youth romantic comedy is wrong as i expected": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx185810-CAzwGw4gYdEr.jpg",
  "look forward for the next death game": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/nx106957-1IM9tyrFORMQ.png",
  "ship of theseus": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx100129-n4GJMMdDRyUh.jpg",
  "neon genesis evangelion": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30698-0niTa3yn2rNK.png",
  "happiness": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx86136-CJRGk54qB6Ev.jpg",
  "lunar legend tsukihime": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30705-SoAVZ3WsyoB5.jpg",
  "death note": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx30021-FE6kmrfpuKyb.jpg",
  "overlord": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx85934-QbxLx34J8D4o.png",
  "chiruran, shinsengumi requiem": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx82005-hw4GjRGAvcpG.jpg",
  "pseudo harem": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx105577-rPJMdZLpfU7E.jpg",
  "she is more ordinary that i expected": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx95436-7u6MUB8cuRBZ.png",
  "godhand teru: the silence corona 2020": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx120274-Gkk0ypt7Rf78.jpg",
  "the blue orchestra": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx101831-0tsq2z822evw.jpg",
  "chion and the cat temple": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/bx98048-md1WoTfB6T5R.jpg"
};
